### ISSUE TITLE
Some Fonts Are Bold by Default and Only Need to Meet 3 to 1 Color Contrast when large

### ISSUE THREAD

**Issue by goodwitch** [dequelabs/axe-core#2089]
Axe is reporting 3 color contrast fails on this page: https://citiqa.mindsmack.com/supportfemalemusic  (this URL content may change quickly so I'm also including code snippets).

font-family: "Interstate-Bold";
font-size: 20px;

Axe reports: 
Element has insufficient color contrast of 3.16 (foreground color: #ffffff, background color: #ff40b4, font size: 15.0pt (20px), font weight: normal). Expected contrast ratio of 4.5:1

WCAG 2.x glossary definition: large scale (text) with at least 18 point or 14 point bold or font size that would yield equivalent size for Chinese, Japanese and Korean (CJK) fonts 

Expectation: Interstate-Bold at 15.0 pt(20px) only needs to meet 3 to 1 because the FONT is bold itself.

Actual: Axe is inaccurately reporting a WCAG 2.x failure of 1.4.3

Motivation: Please account for fonts that are bold by default..and do not fail this. 

axe-core version: 3.4.0
axe-browser extension: 4.2.1

Browser Firefox 74 on Mac 10.15.3

<img width="1129" alt="Screen Shot 2020-03-10 at 12 55 09 PM" src="https://user-images.githubusercontent.com/8203866/76344215-3a0e7600-62cf-11ea-80c3-85d7aff053cb.png">

(This issue was brought to me by Todd Liebsch).

**Comment by straker** [comment]
Took a look at the stylesheets while we still had the site and they are correctly declaring `font-weight` and `font-style` inside the `@font-face` declaration for the font:

```css
@font-face {
    font-family: 'Interstate-Bold';
    src: url('Interstate-Bold.eot');
    src: local('Interstate-Bold'),
        url('Interstate-Bold.eot?#iefix') format('embedded-opentype'),
        url('Interstate-Bold.woff2') format('woff2'),
        url('Interstate-Bold.woff') format('woff'),
        url('Interstate-Bold.ttf') format('truetype'),
        url('Interstate-Bold.svg#Interstate-Regular') format('svg');
    font-weight: bold;
    font-style: bold;
}
```

They also correctly don't set the `font-style` and `font-weight` on the [element itself](https://www.smashingmagazine.com/2013/02/setting-weights-and-styles-at-font-face-declaration/), so they remain as `normal` for both (which is where the problem occurs in our code).  

This means that to get true font-style and font-weights for custom fonts, we're going to need to look at the CSS and find the `@font-face` declaration for the custom font and grab the styles from there.
