### ISSUE TITLE
color-contrast-matches isClipped function catches too much

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#3037]
On https://www.drupal.nl/, none of the anchor elements in the top-nav are flagged by color-contrast (even though they should all fail). Turns out the parent `nav` element is marked as hidden by our `is-visible` function in the color-contrast-matcher because it uses a CSS clip but doesn't do it to try to hide the element from screen readers.

```css
.js .nav-collapse {
    clip: rect(0 0 0 0);
    max-height: none;
    position: relative;
    display: block;
    overflow: hidden;
    zoom: 1;
}
```
