### ISSUE TITLE
Run Firefox CI tests in a separate job

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#3653]
When running CircleCI, the `test_unix` job runs the following jobs:

```yml
      - run: npm run test -- --browsers Chrome,Firefox
      - run: npm run test:integration:chrome
      - run: npm run test:integration:firefox
```

Because the `test_unix` job is blocking all other tests, we have to wait for both Chrome and Firefox tests to complete before everything else can run. While it certainly makes sense to wait for one of them, waiting for tests of both browsers before we run everything else seems unnecessary. It would be better to split the `test_unix` job into a `test_chrome` and `test_firefox` job. We can run the Chrome job first, and run the firefox job in parallel with all other test jobs.
