### ISSUE TITLE
New Rule: css-orientation-is-not-locked

### ISSUE THREAD

**Issue by jkodu** [dequelabs/axe-core#851]
# css-orientation-is-not-locked

The rule should test that the content is not locked to any specific display orientation, and functionality of the content is operable in all display orientations (portrait/ landscape).

**Tags:** wcag21, wcag262

## Matcher

Element(s) to be tested is deciphered at run-time based on the tag(s) for which the orientation style is applied.

## Checks

**Needs review**
Check media-queries targeting orientation, and look for transform styles applied to any elements, which aims to lock orientation.

An example snippet is as below:
```css
@media screen and (min-width: 320px) and (max-width: 767px) and (orientation: landscape) {
  html {
    transform: rotate(-90deg);
    transform-origin: left top;
    width: 100vh;
    overflow-x: hidden;
    position: absolute;
    top: 100%;
    left: 0;
  }
}
```

**Note**: This should also cover portrait mode.

## Proposal
Refer - https://github.com/dequelabs/axe-core/issues/906
